services:
  backend:
    container_name: server
    build:
      context: ./Server
    ports:
      - 8000:8000

  frontend:
    container_name: client
    build:
      context: ./Client
    ports:
      - 80:80
    depends_on:
      - backend