#Use an official Node.js image
FROM node:22

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./


# Copy the rest of the project
COPY . .

# Install dependencies
RUN npm install

# Expose the backend port
EXPOSE 8000

# Start the application
CMD ["node", "index.js"]