#Use an official Node.js image
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy the rest of the project
COPY . .

# Expose the backend port
EXPOSE 8000

# Start the application
CMD ["node", "index.js"]